"""create messages and sessions

Revision ID: 7146e7ac2e53
Revises: 9f1e3b6c2a74
Create Date: 2026-10-04 11:47:10.478303

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7146e7ac2e53"
down_revision: str | Sequence[str] | None = "9f1e3b6c2a74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("base_prompt_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'completed')", name=op.f("ck_sessions_valid_status")
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_sessions_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["base_prompt_id"],
            ["prompts.id"],
            name=op.f("fk_sessions_base_prompt_id_prompts"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(
        op.f("ix_sessions_agent_id"), "sessions", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_sessions_base_prompt_id"), "sessions", ["base_prompt_id"], unique=False
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("questions", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("reply_to_id", sa.Uuid(), nullable=True),
        sa.Column("base_proposal_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('user', 'assistant')", name=op.f("ck_messages_valid_role")
        ),
        sa.CheckConstraint(
            "reply_to_id IS NULL OR reply_to_id <> id",
            name=op.f("ck_messages_not_self_reply"),
        ),
        sa.ForeignKeyConstraint(
            ["base_proposal_id"],
            ["prompt_proposals.id"],
            name=op.f("fk_messages_base_proposal_id_prompt_proposals"),
        ),
        sa.ForeignKeyConstraint(
            ["reply_to_id"],
            ["messages.id"],
            name=op.f("fk_messages_reply_to_id_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_messages_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        op.f("ix_messages_base_proposal_id"),
        "messages",
        ["base_proposal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messages_reply_to_id"), "messages", ["reply_to_id"], unique=False
    )
    op.create_index(
        op.f("ix_messages_session_id"), "messages", ["session_id"], unique=False
    )
    op.add_column("prompt_proposals", sa.Column("message_id", sa.Uuid(), nullable=True))
    op.create_unique_constraint(
        op.f("uq_prompt_proposals_message_id"), "prompt_proposals", ["message_id"]
    )
    op.create_foreign_key(
        op.f("fk_prompt_proposals_message_id_messages"),
        "prompt_proposals",
        "messages",
        ["message_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_prompt_proposals_message_id_messages"),
        "prompt_proposals",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("uq_prompt_proposals_message_id"), "prompt_proposals", type_="unique"
    )
    op.drop_column("prompt_proposals", "message_id")
    op.drop_index(op.f("ix_messages_session_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_reply_to_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_base_proposal_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_base_prompt_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_agent_id"), table_name="sessions")
    op.drop_table("sessions")
    # ### end Alembic commands ###
