"""change agent context to text

Revision ID: e5d620b8c15e
Revises: a76ef3b57d21
Create Date: 2026-09-26 10:55:52.375431

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5d620b8c15e"
down_revision: str | Sequence[str] | None = "a76ef3b57d21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agents",
        "context",
        existing_type=sa.VARCHAR(length=300),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agents",
        "context",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=300),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
